[package]
name = "sgx_server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sgx_server"
path = "src/main.rs"

[dependencies]
async-trait = "0.1.57"

# Server
axum = {version = "0.6.1", features = ["ws", "headers", "macros"]}
axum-jrpc = "0.3.2"
axum-server = { version = "0.4.4", features = ["tls-rustls"] }


tokio = { version = "1.23.0", features = ["full"] }

tower-http = { version = "0.3.4", features = ["cors","fs", "trace"] }

urlencoding = "2.1.2"

tracing = "0.1.37"
tracing-subscriber = { version = "0.3.11", features = ["env-filter", "fmt"] }

serde_json = "1.0"
serde = { version = "1.0.138", features = ["derive"] }

hex = "0.4.3"
base64 = "0.20.0"
log = "0.4.17"
chrono = "0.4.23"

rand = "0.8.5"
clap = { version = "4.0.29", features = ["derive"] }
sysinfo = "0.27.0"
anyhow = "1.0.66"

# IPFS
futures = "0.3.21"
tokio-test = "0.4.2"

# Ternoa/Polkadot
subxt = { git = "https://github.com/paritytech/subxt.git" }
sp-keyring = "12.0.0"
sp-core = { version = "11.0.0", default-features = false, features = ["full_crypto"] }
sp-runtime = { version = "12.0.0" }
parity-scale-codec = { version = "3.2.1", features = ["derive", "full", "bit-vec"] }

# Crypto / Keys
schnorrkel = "0.10.2"
curve25519-dalek = { version = "4.0.0", package = "curve25519-dalek-ml" }
ed25519-dalek = "1.0"
sha256 = "1.1.1"
sequoia-openpgp = "1.13.0"
sigstore = "0.6.0"