[package]
name = "sgx_server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sgx_server"
path = "src/main.rs"

[dependencies]
async-trait = "0.1.61"

# Server
axum = {version = "0.6.2", features = ["ws", "headers", "macros"]}
axum-jrpc = "0.3.2"
axum-server = { version = "0.4.4", features = ["tls-rustls"] }

tokio = { version = "1.25", features = ["full"] }

tower-http = { version = "0.3.5", features = ["cors","fs", "trace"] }

urlencoding = "2.1.2"

tracing = "0.1.37"
tracing-subscriber = { version = "0.3.11", features = ["env-filter", "fmt"] }

# codec
serde_json = "1.0.91"
serde = { version = "1.0.152", features = ["derive"] }
josekit = "0.8.1"
hex = "0.4.3"
base64 = "0.21.0"

log = "0.4.17"
chrono = "0.4.23"

rand = "0.8.5"
clap = { version = "4.0.29", features = ["derive"] }
sysinfo = "0.27.0"
anyhow = "1.0.68"

# IPFS
futures = "0.3.25"
tokio-test = "0.4.2"

# Ternoa/Polkadot
parity-scale-codec = { version = "3.2.1", default-features = false, features = ["derive", "full", "bit-vec"] }

subxt = { git = "https://github.com/paritytech/subxt.git" , features = ["substrate-compat"]}
sp-keyring = "12.0.0"
sp-runtime = { version = "12.0.0" }
sp-core = { version = "11.0.0", default-features = false, features = ["full_crypto"] }

# Crypto / Keys
schnorrkel = "0.10.2"
sha256 = "1.1.1"
sequoia-openpgp = "1.13.0"
sigstore = {git = "https://github.com/sigstore/sigstore-rs.git"}
