[package]
name = "sgx_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"

# Server
axum = {version = "0.6.1", features = ["ws", "headers", "macros"]}
axum-jrpc = "0.2.1"
axum-server = { version = "0.4.2", features = ["tls-rustls"] }

tokio = { version = "1.20.1", features = ["full"] }

tower-http = { version = "0.3.4", features = ["cors","fs", "trace"] }

tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

serde_json = "1.0"
serde = { version = "1.0.138", features = ["derive"] }
hex = "0.4.3"
hex-literal = "0.3.4"

log = "0.4.17"
chrono = "0.4.23"

rand = "0.8.5"
clap = { version = "4.0.29", features = ["derive"] }

# IPFS
futures = "0.3.21"
tokio-test = "0.4.2"

# Ternoa/Polkadot
subxt = "0.23.0"
sp-keyring = "6.0.0"
sp-core = { git = "https://github.com/capsule-corp-ternoa/substrate", tag = "ternoa-substrate-2022-07-30" }
sp-runtime = { git = "https://github.com/capsule-corp-ternoa/substrate", tag = "ternoa-substrate-2022-07-30" }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full", "bit-vec"] }

# Crypto / Keys
pkcs5 = "0.5.0"

# Threshold Crypto
curve25519-dalek = { version = "4.0.0", package = "curve25519-dalek-ml" }
ed25519-dalek = "1.0"
