[package]
name = "signer_bin"
version = "0.5.1"
edition = "2021"

[[bin]]
name = "sgx_signer"
path = "src/main.rs"

[dependencies]

# Client
reqwest = "0.11.16"

tokio = { version = "1.27", features = ["full"] }
tokio-util = "0.7.7"
tokio-stream = { version="0.1.12", features = ["net"] }
tokio-cron-scheduler = "0.9.4"

tower-http = { version = "0.4", features = ["cors","fs", "trace", "timeout"] }
tower = {version = "0.4.13", features = ["timeout"]}

# codec
serde_json = "1.0.95"
serde = { version = "1.0.159", features = ["derive"] }
hex = "0.4.3"
base64 = "0.21.0"
binrw = "0.14.0"

tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "fmt"] }

rand = "0.8.5"
clap = { version = "4.2.1", features = ["derive"] }
anyhow = "1.0.70"

futures = "0.3.27"

# Ternoa/Polkadot
parity-scale-codec = { version = "3.6.5", default-features = false, features = ["derive", "full", "bit-vec"] }
subxt = { version = "0.36.0" , features = ["substrate-compat"]}

# Crypto / Keys
sha256 = "1.1.2"

[features]
default = ["alphanet"]
mainnet = []
alphanet = []
dev1 = []
dev0 = []
