name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Nettle
      run: sudo apt install -y clang llvm pkg-config nettle-dev
    
    - name: Build
      run: cargo build --release --verbose
    
    - name: Run tests
      run: cargo test --verbose
    
    - name: Install Cosign
      if: github.event_name != 'pull_request'
      uses: sigstore/cosign-installer@main
    
    - name: Check install!
      run: cosign version
  
    - name: Sign the binary
      if: ${{ github.event_name != 'pull_request' }}
      run: cosign sign-blob --key ${{secrets.COSIGN_KEY}} target/release/sgx_server --output-file target/release/sgx_server.sig

    - name: Upload binary to release
      if: github.event_name != 'pull_request'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/sgx_server
        asset_name: sgx_server
        tag: ${{ github.ref }}
        overwrite: true
        body: "Ternoa TEE Server"
    
    - name: Upload binary signature to release
      if: github.event_name != 'pull_request'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/sgx_server.sig
        asset_name: sgx_server.sig
        tag: ${{ github.ref }}
        overwrite: true
        body: "Ternoa TEE Server Signature"
